locale = "it"
label = "Italiano"
weight = 1
title = "Archivio di Andrea Pesenti"

[params]
  displayName = "IT"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = ""
  description = "Archivio personale: appunti scolastici, materiali di studio e risorse"

[params.author]
  name = ""
  image = ""
  headline = ""
  bio = ""
